name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t mlops_image:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.userName}} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.password}} # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true
        
    - name: Push Image
      run: |
        docker tag mlops2 salmakishk/mlops_first_docker && \
        docker push salmakishk/mlops_first_docker
